

rankedKeywordsJson = {
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "url": "http://jobview.monster.com/Senior-IT-Database-Analyst-Multiple-Locations-Job-Boston-MA-US-170200057.aspx?mescoid=1500142001001",
    "totalTransactions": "1",
    "language": "english",
    "keywords": [
        {
            "relevance": "0.991817",
            "text": "health care"
        },
        {
            "relevance": "0.84722",
            "text": "health care industry"
        },
        {
            "relevance": "0.798642",
            "text": "cloud infrastructure"
        },
        {
            "relevance": "0.794904",
            "text": "UnitedHealth Group"
        },
        {
            "relevance": "0.78666",
            "text": "SQL Server"
        }
    ]
}



$.ajax({
    url: 'http://api.wunderground.com/api/36b799dc821d5836/conditions/q/UK/London.json',
    dataType: 'jsonp',
    data: '?',
    success: function(weatherData){
        if (weatherData["current_observation"] != null
           && typeof weatherData["current_observation"] === 'object')
           DisplayWeather(weatherData["current_observation"]);
    }
});



function rankedKeywords()
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", "https://gateway-a.watsonplatform.net/calls/url/URLGetRankedKeywords?apikey=e1988a049c6961aca0a370068dcf5a0140521026&outputMode=json&url=http://jobview.monster.com/Senior-IT-Database-Analyst-Multiple-Locations-Job-Boston-MA-US-170200057.aspx?mescoid=1500142001001&jobPosition=1", false ); // false for synchronous request
    xmlHttp.send( null );
    return xmlHttp.responseText;
}
